databases:
  - name: apollo-db
    databaseName: apollo
    user: apollo
    plan: free
    region: frankfurt

services:
  - type: web
    name: apollo-backend
    runtime: python
    region: frankfurt
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt && pip install -e .
    startCommand: cd src && gunicorn apollo_backend.main:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: apollo-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.13.0

  - type: web
    name: apollo-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
